services:
  - type: web
    name: reachinbox-onebox
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build && cd .. && mkdir -p dist && cp -r frontend/dist/* dist/
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
